version: '3'
services:

  # redis
  psl-redis:
    image: redis:latest

  # elastic stack
  psl-es:
    image: elasticsearch:alpine
    ports:
      - 9200:9200
  psl-logstash:
    image: blacktop/logstash:latest
    depends_on:
      - psl-es
      - psl-redis
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
    command: logstash -f /etc/logstash/conf.d/logstash.conf
  psl-kibana:
    image: kibana:latest
    depends_on:
      - psl-es
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: "http://psl-es:9200"

  # rsyslog
  psl-rsyslog:
    build: ./rsyslog
    depends_on:
      - psl-redis
    ports:
      - 514:514
      - 514:514/udp
    volumes:
      - ./rsyslog/logs/:/var/log/
      - ./rsyslog/rsyslog.conf:/etc/rsyslog.conf

  # python project
  psl-project:
    image: python:3-alpine
    command: sh -c "pip install -r /root/requirements.txt && python /root/app.py"
    volumes:
      - ./project/requirements.txt:/root/requirements.txt
      - ./project/app.py:/root/app.py
    depends_on:
      - psl-rsyslog
