version: '3'
services:

  # elastic stack
  psl-es:
    image: elasticsearch:alpine
    ports:
      - 9200:9200
  psl-logstash:
    image: logstash:alpine
    depends_on:
      - psl-es
    expose:
      - 5959
    volumes:
      - ./logstash:/logstash
    command: logstash -f "/logstash/*.conf"  -w8 --pipeline-batch-size 1000 --auto-reload
  psl-kibana:
    image: kibana:latest
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: "http://psl-es:9200"

  # redis
  psl-redis:
    image: redis:latest

  # rsyslog
  psl-rsyslog:
    build: ./rsyslog
    depends_on:
      - psl-redis

  # python project
  psl-project:
    image: python:3-alpine
    command: sh -c "pip install -r /root/requirements.txt && python /root/app.py"
    volumes:
      - ./project/requirements.txt:/root/requirements.txt
      - ./project/app.py:/root/app.py
    depends_on:
      - psl-rsyslog
